version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"     # cổng AMQP cho app connect
      - "15672:15672"   # cổng web quản lý RabbitMQ
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - ecommerce

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ecommerce

  product:
    build: ./product
    container_name: product
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - PORT=3001
      - MONGODB_PRODUCT_URI=mongodb://mongo:27017/products
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
    networks:
      - ecommerce

  order:
    build: ./order
    container_name: order
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - PORT=3002
      - MONGODB_ORDER_URI=mongodb://mongo:27017/orders
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_QUEUE=orders
    networks:
      - ecommerce

  auth:
    build: ./auth
    container_name: auth
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_started
    environment:
      - PORT=3000
      - MONGODB_AUTH_URI=mongodb://mongo:27017/auth
    networks:
      - ecommerce

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    environment:
      - PORT=3003
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  mongo_data:
